# Generated by Django 5.1.1 on 2024-09-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_rename_date_material_date_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date',
            new_name='date_worked',
        ),
    ]
