# Generated by Django 5.1.1 on 2024-09-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_rename_date_employee_date_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_worked',
            new_name='date',
        ),
    ]
