# Generated by Django 5.1.1 on 2024-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_rename_date_worked_employee_date'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='employee',
        #     name='role_of_the_employee',
        #     field=models.CharField(default='Worker', max_length=50),
        # ),
        migrations.AddField(
            model_name='employee',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
