# Generated by Django 5.1.1 on 2024-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_employee_role_employee_unique_identifier'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='employee',
        #     name='role',
        #     field=models.CharField(default='Worker', max_length=50),
        # ),
        migrations.AlterField(
            model_name='employee',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
