# Generated by Django 5.1.1 on 2024-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_employee_role_alter_employee_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Worker', max_length=50),
        ),
    ]
