# Generated by Django 5.1.1 on 2024-09-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='date',
            new_name='date_used',
        ),
        migrations.AlterField(
            model_name='employee',
            name='days_worked',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
